"use client"

import { useEffect, useState } from "react"
import { getDb } from "@/lib/firebase/firebaseApp"
import { doc, getDoc } from "firebase/firestore"
const db = getDb
export default function ImpactCounter() {

  const [metrics, setMetrics] = useState<any>(null)

  useEffect(() => {

    const loadMetrics = async () => {

      const docRef = doc(db(), "impact_metrics", "global")
      const snapshot = await getDoc(docRef)

      if (snapshot.exists()) {
        setMetrics(snapshot.data())
      }

    }

    loadMetrics()

  }, [])

  if (!metrics) return null

  return (

    <section className="py-20 bg-gray-100 text-center">

      <h2 className="text-3xl font-bold mb-10">
        Impact Generated by the NdaY'Fako Ecosystem
      </h2>

      <div className="grid grid-cols-4 gap-10 max-w-5xl mx-auto">

        <div>
          <h3 className="text-4xl font-bold text-green-600">
            {metrics.waste_collected} kg
          </h3>
          <p>Waste Collected</p>
        </div>

        <div>
          <h3 className="text-4xl font-bold text-blue-600">
            {metrics.waste_recycled} kg
          </h3>
          <p>Waste Recycled</p>
        </div>

        <div>
          <h3 className="text-4xl font-bold text-purple-600">
            {metrics.co2_avoided} kg
          </h3>
          <p>CO₂ Avoided</p>
        </div>

        <div>
          <h3 className="text-4xl font-bold text-orange-600">
            {metrics.operators_active}
          </h3>
          <p>Active Operators</p>
        </div>

      </div>

    </section>

  )
}